import {
  Class,
  Subject,
  Term,
  Student,
  GradingScale,
  GradeSubmission,
} from "@/types/result"

export const DUMMY_CLASSES: Class[] = [
  { id: "1", name: "SSS1 A", level: "Senior Secondary" },
  { id: "2", name: "SSS1 B", level: "Senior Secondary" },
  { id: "3", name: "SSS2 A", level: "Senior Secondary" },
  { id: "4", name: "SSS2 B", level: "Senior Secondary" },
  { id: "5", name: "SSS3 A", level: "Senior Secondary" },
  { id: "6", name: "SSS3 B", level: "Senior Secondary" },
  { id: "7", name: "JSS1 A", level: "Junior Secondary" },
  { id: "8", name: "JSS1 B", level: "Junior Secondary" },
  { id: "9", name: "JSS2 A", level: "Junior Secondary" },
  { id: "10", name: "JSS2 B", level: "Junior Secondary" },
]

export const DUMMY_SUBJECTS: Subject[] = [
  { id: "1", name: "Mathematics", code: "MATH" },
  { id: "2", name: "English Language", code: "ENG" },
  { id: "3", name: "Physics", code: "PHY" },
  { id: "4", name: "Chemistry", code: "CHEM" },
  { id: "5", name: "Biology", code: "BIO" },
  { id: "6", name: "Computer Science", code: "COMP" },
  { id: "7", name: "Economics", code: "ECON" },
  { id: "8", name: "Geography", code: "GEO" },
  { id: "9", name: "History", code: "HIST" },
  { id: "10", name: "French", code: "FREN" },
  { id: "11", name: "Further Mathematics", code: "FUR-MATH" },
  { id: "12", name: "Agricultural Science", code: "AGRIC" },
]

export const DUMMY_TERMS: Term[] = [
  { id: "1", name: "1st Term", academic_year: "2024/2025", is_active: true },
  { id: "2", name: "2nd Term", academic_year: "2024/2025", is_active: false },
  { id: "3", name: "3rd Term", academic_year: "2024/2025", is_active: false },
  { id: "4", name: "1st Term", academic_year: "2023/2024", is_active: false },
  { id: "5", name: "2nd Term", academic_year: "2023/2024", is_active: false },
  { id: "6", name: "3rd Term", academic_year: "2023/2024", is_active: false },
]

export const DUMMY_STUDENTS: Student[] = [
  {
    id: "1",
    first_name: "Rechukwu",
    last_name: "Farwar",
    registration_number: "STD001",
    class: "SSS1 B",
  },
  {
    id: "2",
    first_name: "Eastern",
    last_name: "Kingsley",
    registration_number: "STD002",
    class: "SSS1 B",
  },
  {
    id: "3",
    first_name: "Joy",
    last_name: "Owen",
    registration_number: "STD003",
    class: "SSS1 B",
  },
  {
    id: "4",
    first_name: "Christian",
    last_name: "Ogachukwu",
    registration_number: "STD004",
    class: "SSS1 B",
  },
  {
    id: "5",
    first_name: "Tamuro",
    last_name: "Preye",
    registration_number: "STD005",
    class: "SSS1 B",
  },
  {
    id: "6",
    first_name: "Furmidi",
    last_name: "Mantai",
    registration_number: "STD006",
    class: "SSS1 B",
  },
  {
    id: "7",
    first_name: "Uadax",
    last_name: "Favour",
    registration_number: "STD007",
    class: "SSS1 B",
  },
  {
    id: "8",
    first_name: "Chinazo",
    last_name: "Favour",
    registration_number: "STD008",
    class: "SSS1 B",
  },
  {
    id: "9",
    first_name: "Johnson",
    last_name: "Yerni",
    registration_number: "STD009",
    class: "SSS1 B",
  },
  {
    id: "10",
    first_name: "Ilechukwu",
    last_name: "Farvour",
    registration_number: "STD010",
    class: "SSS1 B",
  },
  {
    id: "11",
    first_name: "Blessing",
    last_name: "Okon",
    registration_number: "STD011",
    class: "SSS2 A",
  },
  {
    id: "12",
    first_name: "David",
    last_name: "Mark",
    registration_number: "STD012",
    class: "SSS2 A",
  },
]

export const DUMMY_GRADING_SCALE: GradingScale[] = [
  { grade: "A", min_score: 80, max_score: 100, remark: "Excellent" },
  { grade: "B", min_score: 70, max_score: 79, remark: "Very Good" },
  { grade: "C", min_score: 60, max_score: 69, remark: "Good" },
  { grade: "D", min_score: 50, max_score: 59, remark: "Credit" },
  { grade: "E", min_score: 40, max_score: 49, remark: "Pass" },
  { grade: "F", min_score: 0, max_score: 39, remark: "Fail" },
]

// Mock grade submissions for admin
export const DUMMY_SUBMISSIONS: GradeSubmission[] = [
  {
    id: "1",
    teacher_id: "teacher1",
    class_id: "SSS1 B",
    subject_id: "Mathematics",
    term_id: "1",
    grades: [],
    status: "submitted",
    submitted_at: "2024-11-20T10:00:00Z",
    created_at: "2024-11-20T09:00:00Z",
    updated_at: "2024-11-20T10:00:00Z",
    academic_session_id: "2024/2025",
  },
  {
    id: "2",
    teacher_id: "teacher2",
    class_id: "SSS2 A",
    subject_id: "Biology",
    term_id: "1",
    grades: [],
    status: "approved",
    submitted_at: "2024-11-19T14:30:00Z",
    reviewed_at: "2024-11-20T09:00:00Z",
    created_at: "2024-11-19T14:00:00Z",
    updated_at: "2024-11-20T09:00:00Z",
    academic_session_id: "2024/2025",
  },
  {
    id: "3",
    teacher_id: "teacher1",
    class_id: "JSS1 A",
    subject_id: "Chemistry",
    term_id: "1",
    grades: [],
    status: "approved",
    submitted_at: "2024-11-18T11:00:00Z",
    reviewed_at: "2024-11-19T10:00:00Z",
    created_at: "2024-11-18T10:00:00Z",
    updated_at: "2024-11-19T10:00:00Z",
    academic_session_id: "2024/2025",
  },
  {
    id: "4",
    teacher_id: "teacher3",
    class_id: "JSS2 B",
    subject_id: "Physics",
    term_id: "1",
    grades: [],
    status: "submitted",
    submitted_at: "2024-11-21T08:00:00Z",
    created_at: "2024-11-20T16:00:00Z",
    updated_at: "2024-11-21T08:00:00Z",
    academic_session_id: "2024/2025",
  },
]

// Mock student results for parent/student view
export const DUMMY_STUDENT_RESULTS = [
  {
    subject_id: "1",
    subject_name: "Mathematics",
    ca_score: 18,
    exam_score: 30,
    total_score: 48,
    grade: "C",
  },
  {
    subject_id: "2",
    subject_name: "English Language",
    ca_score: 27,
    exam_score: 51,
    total_score: 78,
    grade: "A",
  },
  {
    subject_id: "3",
    subject_name: "Chemistry",
    ca_score: 20,
    exam_score: 45,
    total_score: 65,
    grade: "B",
  },
  {
    subject_id: "4",
    subject_name: "Physics",
    ca_score: 18,
    exam_score: 30,
    total_score: 80,
    grade: "A",
  },
  {
    subject_id: "5",
    subject_name: "Biology",
    ca_score: 18,
    exam_score: 30,
    total_score: 48,
    grade: "C",
  },
  {
    subject_id: "6",
    subject_name: "Computer Science",
    ca_score: 40,
    exam_score: 30,
    total_score: 70,
    grade: "A",
  },
  {
    subject_id: "7",
    subject_name: "Economics",
    ca_score: 18,
    exam_score: 30,
    total_score: 44,
    grade: "C",
  },
  {
    subject_id: "8",
    subject_name: "Geography",
    ca_score: 18,
    exam_score: 30,
    total_score: 50,
    grade: "B",
  },
]

// Teacher names for admin submissions
export const TEACHER_NAMES: { [key: string]: string } = {
  teacher1: "Miss Chinazo Favour",
  teacher2: "Mr Johnson Yerni",
  teacher3: "Mrs Adebayo Grace",
  teacher4: "Mr Emmanuel Okafor",
  teacher5: "Miss Precious Adekunle",
}
