import { FeatureProps } from "./features.type"

export const featuresData: FeatureProps[] = [
  {
    number: 1,
    title: "Authentication & Security",
    description: "Give every user secure access with strict permission controls.",
    imageSrc: "/images/features/image1.png",
    listItems: [
      "Role-based access (Super Admin, Admin, Teacher, Parent, Student)",
      "Secure login + logout",
      "Password reset via email token",
      "Account lockout after multiple failed attempts",
      "Full audit logs for login and security events",
    ],
  },
  {
    number: 2,
    title: "Attendance Features",
    description:
      "Digitize daily attendance for teachers and students with real-time accuracy.",
    imageSrc: "/images/features/image2.png",
    imgWidth: 410,
    imgHeight: 480,
    listItems: [
      "Daily student attendance",
      "Teacher check-in via web or NFC tap",
      "NFC attendance using the mobile app",
      "Offline attendance queue + auto-sync",
      "Admin dashboard for attendance summaries",
      "Edit logs with full audit history",
    ],
  },
  {
    number: 3,
    title: "Fees & Payments Features",
    description: "Manage school fees with clarity, transparency, and accurate records.",
    imageSrc: "/images/features/image3.png",
    imgWidth: 540,
    imgHeight: 447,
    listItems: [
      "Create fee groups and items (Tuition, Boarding, Exam Fees)",
      "Bulk upload student debts",
      "Record full or part payments",
      "Fee reminders and notifications",
      "Individual ledger per student",
      "Complete payment audit trail per student",
    ],
  },
  {
    number: 4,
    title: "Academics Features",
    description: "Set up and manage your school's academic structure in minutes.",
    imageSrc: "/images/features/image4.png",
    imgWidth: 517,
    imgHeight: 480,
    listItems: [
      "Class and arm (stream) setup",
      "Assign subjects to classes",
      "Teacher-Class-Subject mapping",
      "Daily and weekly timetables",
      "Conflict detection for class, teacher, and room schedules",
    ],
  },
  {
    number: 5,
    title: "Exam & Results Features",
    description: "Handle assessments and results from start to finish in one place.",
    imageSrc: "/images/features/image5.png",
    imgWidth: 572,
    imgHeight: 555,
    listItems: [
      "Continuous assessment entry",
      "Exam score entry",
      "Automatic result computation",
      "Admin approval workflow",
      "Printable digital report sheets (PDF)",
      "Student and parent access to results",
    ],
  },
  {
    number: 6,
    title: "Parent/Student Functions",
    description: "Simple, transparent access to academic information.",
    imageSrc: "/images/features/image6.png",
    imgWidth: 656,
    imgHeight: 623,
    listItems: [
      "View academic results",
      "View attendance history",
      "Check current fee balance",
      "Admin approval workflow",
      "Access term updates and school notices",
    ],
  },
  {
    number: 7,
    title: "Admin Tools",
    description: "Powerful controls for running and monitoring school operations.",
    imageSrc: "/images/features/image7.png",
    imgWidth: 672,
    imgHeight: 675,
    listItems: [
      "School-wide analytics and dashboards",
      "User management (Admins, Teachers, Students, Parents)",
      "Device management for NFC attendance",
      "Session and term setup",
      "Bulk import for students and teachers",
    ],
  },
]
